services:
  - type: web
    name: image-enhancer-api
    env: python
    buildCommand: pip install -r api/requirements.txt
    startCommand: cd api && gunicorn index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: FLASK_ENV
        value: production 